version: 2

project_name: kzlogviewer

before:
  hooks:
    - go mod tidy

builds:
  - id: kzlogviewer
    main: ./cmd/kzlogviewer
    binary: kzlogviewer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/karozadev/KzLogViewer/internal/version.Version={{ .Version }}
      - -X github.com/karozadev/KzLogViewer/internal/version.Commit={{ .Commit }}
      - -X github.com/karozadev/KzLogViewer/internal/version.Date={{ .Date }}

archives:
  - id: kzlogviewer
    ids:
      - kzlogviewer
    name_template: "kzlogviewer_{{ .Os }}_{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  use: git
  format: "{{ .Message }}"
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^build:"
  groups:
    - title: Features
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: Fixes
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: Performance
      regexp: '^perf(\(.+\))?:'
      order: 2
    - title: Refactoring
      regexp: '^refactor(\(.+\))?:'
      order: 3
    - title: Other changes
      order: 999

release:
  github:
    owner: karozadev
    name: KzLogViewer
  prerelease: auto
