package ports

import "context"

// Release describes a published KzLogViewer release, as found on GitHub.
type Release struct {
	Version     string
	AssetName   string
	DownloadURL string
	PublishedAt string
	// Notes holds the release's changelog text (generated by GoReleaser
	// from Conventional Commits), used to build a cumulative changelog
	// when a user updates across several versions at once.
	Notes string
}

// UpdateChecker looks up available releases.
type UpdateChecker interface {
	// LatestRelease returns the single most recent release, used for the
	// lightweight startup check.
	LatestRelease(ctx context.Context) (Release, error)

	// ReleasesSince returns every release strictly newer than
	// currentVersion, sorted oldest first, so their Notes can be
	// concatenated into one cumulative changelog when several versions
	// are skipped at once.
	ReleasesSince(ctx context.Context, currentVersion string) ([]Release, error)
}

// Applier downloads and installs a release in place of the running binary.
type Applier interface {
	Apply(ctx context.Context, release Release) error
}
